### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by mynameisrufus**
No logic changes, just getting this to compile as fast as possible.

Bump minor version incase any breaking changes.

### CODE REVIEW

**Comment by forkfork** [comment]
This one's a dependency of a bunch of services - will this complicate everyones local dev env?

**Comment by mynameisrufus** [comment]
@forkfork no i'm checking in the compiled js in `lib` so will just work as normal. If you want to alter this lib though you need todo the ts bits.

**Comment by forkfork** [comment]
Yeah fair enough. I have horrible memories of coffeescript

**Comment by forkfork** [comment]
Side note - this whole library probably needs to be nuked from orbit at some point.

**Pull request merged**
